[tool.poetry]
name = "data-platform-firebreak-python-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
boto3 = "^1.33.10"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
moto = "^4.2.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
