"""empty message

Revision ID: 65817df3e2f0
Revises: 2bc9da0d5ae0
Create Date: 2024-01-03 15:33:50.610800

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65817df3e2f0"  # pragma: allowlist secret
down_revision: Union[str, None] = "2bc9da0d5ae0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_data_products_name_version", table_name="data_product_versions")
    op.create_index(
        op.f("ix_data_product_versions_name"),
        "data_product_versions",
        ["name"],
        unique=False,
    )
    op.create_index(
        "ix_data_prouduct_versions_name_version",
        "data_product_versions",
        ["name", "version"],
        unique=True,
    )
    op.create_index(
        op.f("ix_data_products_name"), "data_products", ["name"], unique=False
    )
    op.drop_index("ix_schemas_name", table_name="schemas")
    op.create_index(op.f("ix_schemas_name"), "schemas", ["name"], unique=False)
    op.create_index(
        "ix_schemas_name_data_product_id",
        "schemas",
        ["name", "data_product_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_schemas_name_data_product_id", table_name="schemas")
    op.drop_index(op.f("ix_schemas_name"), table_name="schemas")
    op.create_index("ix_schemas_name", "schemas", ["name"], unique=True)
    op.drop_index(op.f("ix_data_products_name"), table_name="data_products")
    op.drop_index(
        "ix_data_prouduct_versions_name_version", table_name="data_product_versions"
    )
    op.drop_index(
        op.f("ix_data_product_versions_name"), table_name="data_product_versions"
    )
    op.create_index(
        "ix_data_products_name_version",
        "data_product_versions",
        ["name", "version"],
        unique=True,
    )
    # ### end Alembic commands ###
