apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-fb-daap-api-deployment
  labels:
    app: dp-fb-daap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-fb-daap-api
  template:
    metadata:
      labels:
        app: dp-fb-daap-api
    spec:
      containers:
        - name: dp-fb-daap-api
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: elasticache-redis
                  key: url
